title: Mir Faiyaz Hossain
logo: assets/img/mir_cv_photo_circular.jpg
# description: I graduated from North South University, Dhaka, with a degree in Computer Science and Engineering. I am passionate about making a meaningful
# impact in the world using the skills and knowledge I’ve acquired. My interests lie deeply in Study, Research, and Teaching.
# show_downloads: true
theme: jekyll-theme-minimal
